version: '3'

services:
    backend:
        build: ./backend
        ports:
          - 4000:4000
        volumes:
          - ./backend/src:/app/src:rw
          - ./backend/package.json:/app/package.json
          - ./backend/node_modules:/app/node_modules
    frontend:
      build: ./frontend
      ports:
        - 3030:3000
      volumes:
        - ./frontend/src:/app/src:rw
    db:
      image: postgres
      environment:
        POSTGRES_USER: good_corner
        POSTGRES_PASSWORD: password
        POSTGRES_DB: goodcornerdb
        PGDATA: customDataFolder
      volumes:
        - ./dbData:/var/lib/postgresql/data/customDataFolder
      ports:
        - 5432:5432
    images:
      build: ./images
      volumes:
      - ./images/src:/app/src
      - ./images/uploads:/app/uploads
      ports:
      - 8000:8000
    adminer:
      image: adminer
      ports:
        - 8080:8080
