import Head from "next/head";
import Header from "./Header";
import { ReactNode, useEffect, useState } from "react";
import { gql, useQuery } from "@apollo/client";
import router from "next/router";
import { CurrentUser } from "@/types/users.type";
import { AuthContext } from "@/context/authContext";

const GET_USER = gql`
  query Query {
    getUser {
      id
      role
    }
  }
`;

const Layout = ({ children }: { children: ReactNode }) => {
  const { loading, error, data } = useQuery(GET_USER);
  const token = localStorage.getItem("token");
  const [currentUser, setCurrentUser] = useState<CurrentUser | null>(null);

  useEffect(() => {
    if (!token) {
      localStorage.removeItem("token");
      router.push("/signin");
    }
    if (token && data && !loading) {
      setCurrentUser({ ...data.getUser });
    }
  }, [token, loading, data]);

  return (
    <AuthContext.Provider value={{ currentUser, setCurrentUser }}>
      <Head>
        <title>The Good Corner</title>
        <meta name="description" content="Generated by create nex app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main-content">{children}</main>
    </AuthContext.Provider>
  );
};

export default Layout;
